// Code generated by go generate; DO NOT EDIT.

package appointment

import (
	"github.com/arfis/waiting-room/nghis-adapter/internal/data/dto"
	ngErrors "github.com/arfis/waiting-room/nghis-adapter/internal/errors"
	"github.com/arfis/waiting-room/nghis-adapter/internal/rest/handler"
	"github.com/arfis/waiting-room/nghis-adapter/internal/service/appointment"
	"log/slog"
	"net/http"
)

type Handler struct {
	svc                  *appointment.Service
	responseErrorHandler *ngErrors.ResponseErrorHandler
}

func New(
	svc *appointment.Service,
	responseErrorHandler *ngErrors.ResponseErrorHandler,
) *Handler {
	return &Handler{
		svc:                  svc,
		responseErrorHandler: responseErrorHandler,
	}
}

func init() {
	slog.Debug("Generated handler 'appointment/Handler' initialized")
}

func (h *Handler) GetAppointmentsForPatient(w http.ResponseWriter, r *http.Request) {
	var applicationErr error
	nationalID := handler.PathParamToString(r, "nationalID")
	var resp []dto.AppointmentResp
	resp, applicationErr = h.svc.GetAppointmentsForPatient(
		r.Context(),
		nationalID,
	)
	if applicationErr != nil {
		h.responseErrorHandler.HandleAndWriteError(w, r, applicationErr)
		return
	}
	err := handler.WriteJson(r.Context(), w, http.StatusOK, resp)
	if err != nil {
		slog.ErrorContext(r.Context(), "GetAppointmentsForPatient - error writing response", "error", err)
		h.responseErrorHandler.HandleAndWriteError(w, r, err)
		return
	}
}
