// Code generated by go generate; DO NOT EDIT.

package queueentrystatus

import (
	"fmt"
	"github.com/arfis/waiting-room/internal/errors"
)

type QueueEntryStatus string

var (
	UNKNOWN_VALUE QueueEntryStatus = "UNKNOWN_VALUE"
	WAITING       QueueEntryStatus = "WAITING"
	CALLED        QueueEntryStatus = "CALLED"
	IN_SERVICE    QueueEntryStatus = "IN_SERVICE"
	IN_ROOM       QueueEntryStatus = "IN_ROOM"
	COMPLETED     QueueEntryStatus = "COMPLETED"
	SKIPPED       QueueEntryStatus = "SKIPPED"
	CANCELLED     QueueEntryStatus = "CANCELLED"
	NO_SHOW       QueueEntryStatus = "NO_SHOW"
)

// String gets the string representation of the QueueEntryStatus
func (c QueueEntryStatus) String() string {
	return string(c)
}

var _stringToQueueEntryStatus = map[string]QueueEntryStatus{
	string(WAITING):    WAITING,
	string(CALLED):     CALLED,
	string(IN_SERVICE): IN_SERVICE,
	string(IN_ROOM):    IN_ROOM,
	string(COMPLETED):  COMPLETED,
	string(SKIPPED):    SKIPPED,
	string(CANCELLED):  CANCELLED,
	string(NO_SHOW):    NO_SHOW,
}

func StringToQueueEntryStatus(source string) (QueueEntryStatus, error) {
	if v, ok := _stringToQueueEntryStatus[source]; ok {
		return v, nil
	}
	return "UNKNOWN_VALUE", errors.Validation(fmt.Errorf("invalid value ('%s') passed to QueueEntryStatus", source), nil)
}
