// Code generated by go generate; DO NOT EDIT.
package errors

const (
	BusinessErrorCode                 string = "BUSINESS_ERROR"
	ValidationErrorCode               string = "VALIDATION_ERROR"
	MissingRequiredFieldErrorCode     string = "MISSING_REQUIRED_FIELD_ERROR"
	ObjectVersionMismatchErrorCode    string = "OBJECT_VERSION_MISMATCH_ERROR"
	NotFoundErrorCode                 string = "NOT_FOUND_ERROR"
	ServiceCallErrorCode              string = "SERVICE_CALL_ERROR"
	ForbiddenErrorCode                string = "FORBIDDEN_ERROR"
	InternalServerErrorCode           string = "INTERNAL_SERVER_ERROR"
	AuthHeaderCode                    string = "AUTH_HEADER"
	UnprocessableEntityForeignKeyCode string = "UNPROCESSABLE_ENTITY_FOREIGN_KEY"
	UnprocessableEntityUniqueCode     string = "UNPROCESSABLE_ENTITY_UNIQUE"
)
