// Code generated by go generate; DO NOT EDIT.
package errors

import (
	"fmt"
)

const (
	CardReadFailedCode     = "CARD_READ_FAILED"
	InvalidRoomIdCode      = "INVALID_ROOM_ID"
	QueueEmptyCode         = "QUEUE_EMPTY"
	QueueEntryNotFoundCode = "QUEUE_ENTRY_NOT_FOUND"
)

// CardReadFailed - When card reading fails.
func CardReadFailed() *ApplicationError {
	return New(CardReadFailedCode, "Failed to read card data", 400, nil)
}

// InvalidRoomId - When room ID is invalid or doesn't exist.
func InvalidRoomId(params ...any) *ApplicationError {
	return New(InvalidRoomIdCode, fmt.Sprintf("Invalid room ID: %s", params...), 400, nil)
}

// QueueEmpty - When trying to call next but no one is waiting.
func QueueEmpty() *ApplicationError {
	return New(QueueEmptyCode, "Queue is empty", 400, nil)
}

// QueueEntryNotFound - When trying to find a queue entry that doesn't exist.
func QueueEntryNotFound(params ...any) *ApplicationError {
	return New(QueueEntryNotFoundCode, fmt.Sprintf("Queue entry not found: %s", params...), 404, nil)
}
