// Code generated by go generate; DO NOT EDIT.
package dto

import "time"

type AgeConfig struct {
	AgeThresholdSenior   int64   `json:"ageThresholdSenior"`
	Description          *string `json:"description,omitempty"`
	Over65PerYearOlder   float64 `json:"over65PerYearOlder"`
	Under6PerYearYounger float64 `json:"under6PerYearYounger"`
}

func (ageConfig AgeConfig) GetAgeThresholdSenior() int64 {
	return ageConfig.AgeThresholdSenior
}

func (ageConfig AgeConfig) GetDescription() string {
	var v string
	if ageConfig.Description != nil {
		return *ageConfig.Description
	}
	return v
}

func (ageConfig AgeConfig) GetOver65PerYearOlder() float64 {
	return ageConfig.Over65PerYearOlder
}

func (ageConfig AgeConfig) GetUnder6PerYearYounger() float64 {
	return ageConfig.Under6PerYearYounger
}

type Algorithm struct {
	Explanation    []string `json:"explanation,omitempty" validate:"dive"`
	OrderingFields []string `json:"orderingFields,omitempty" validate:"dive"`
}

func (algorithm Algorithm) GetExplanation() []string {
	return algorithm.Explanation
}

func (algorithm Algorithm) GetOrderingFields() []string {
	return algorithm.OrderingFields
}

type AppointmentDeviation struct {
	Description           *string `json:"description,omitempty"`
	EarlyPenaltyPerMinute float64 `json:"earlyPenaltyPerMinute"`
	LateBonusPerMinute    float64 `json:"lateBonusPerMinute"`
}

func (appointmentDeviation AppointmentDeviation) GetDescription() string {
	var v string
	if appointmentDeviation.Description != nil {
		return *appointmentDeviation.Description
	}
	return v
}

func (appointmentDeviation AppointmentDeviation) GetEarlyPenaltyPerMinute() float64 {
	return appointmentDeviation.EarlyPenaltyPerMinute
}

func (appointmentDeviation AppointmentDeviation) GetLateBonusPerMinute() float64 {
	return appointmentDeviation.LateBonusPerMinute
}

type CacheClearResponse struct {
	Message *string `json:"message,omitempty"`
}

func (cacheClearResponse CacheClearResponse) GetMessage() string {
	var v string
	if cacheClearResponse.Message != nil {
		return *cacheClearResponse.Message
	}
	return v
}

type CardReaderStatus struct {
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	Id        string     `json:"id" validate:"required"`
	IpAddress *string    `json:"ipAddress,omitempty"`
	LastError *string    `json:"lastError,omitempty"`
	LastSeen  *time.Time `json:"lastSeen,omitempty"`
	Name      string     `json:"name" validate:"required"`
	Status    string     `json:"status" validate:"required"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	Version   *string    `json:"version,omitempty"`
}

func (cardReaderStatus CardReaderStatus) GetCreatedAt() time.Time {
	var v time.Time
	if cardReaderStatus.CreatedAt != nil {
		return *cardReaderStatus.CreatedAt
	}
	return v
}

func (cardReaderStatus CardReaderStatus) GetId() string {
	return cardReaderStatus.Id
}

func (cardReaderStatus CardReaderStatus) GetIpAddress() string {
	var v string
	if cardReaderStatus.IpAddress != nil {
		return *cardReaderStatus.IpAddress
	}
	return v
}

func (cardReaderStatus CardReaderStatus) GetLastError() string {
	var v string
	if cardReaderStatus.LastError != nil {
		return *cardReaderStatus.LastError
	}
	return v
}

func (cardReaderStatus CardReaderStatus) GetLastSeen() time.Time {
	var v time.Time
	if cardReaderStatus.LastSeen != nil {
		return *cardReaderStatus.LastSeen
	}
	return v
}

func (cardReaderStatus CardReaderStatus) GetName() string {
	return cardReaderStatus.Name
}

func (cardReaderStatus CardReaderStatus) GetStatus() string {
	return cardReaderStatus.Status
}

func (cardReaderStatus CardReaderStatus) GetUpdatedAt() time.Time {
	var v time.Time
	if cardReaderStatus.UpdatedAt != nil {
		return *cardReaderStatus.UpdatedAt
	}
	return v
}

func (cardReaderStatus CardReaderStatus) GetVersion() string {
	var v string
	if cardReaderStatus.Version != nil {
		return *cardReaderStatus.Version
	}
	return v
}

type Contributions struct {
	Age                  *AgeConfig            `json:"age" validate:"required"`
	AppointmentDeviation *AppointmentDeviation `json:"appointmentDeviation" validate:"required"`
	ManualOverride       *ManualOverride       `json:"manualOverride" validate:"required"`
	SymbolWeights        *SymbolWeights        `json:"symbolWeights" validate:"required"`
	WaitingTime          *WaitingTime          `json:"waitingTime" validate:"required"`
}

func (contributions Contributions) GetAge() AgeConfig {
	var v AgeConfig
	if contributions.Age != nil {
		return *contributions.Age
	}
	return v
}

func (contributions Contributions) GetAppointmentDeviation() AppointmentDeviation {
	var v AppointmentDeviation
	if contributions.AppointmentDeviation != nil {
		return *contributions.AppointmentDeviation
	}
	return v
}

func (contributions Contributions) GetManualOverride() ManualOverride {
	var v ManualOverride
	if contributions.ManualOverride != nil {
		return *contributions.ManualOverride
	}
	return v
}

func (contributions Contributions) GetSymbolWeights() SymbolWeights {
	var v SymbolWeights
	if contributions.SymbolWeights != nil {
		return *contributions.SymbolWeights
	}
	return v
}

func (contributions Contributions) GetWaitingTime() WaitingTime {
	var v WaitingTime
	if contributions.WaitingTime != nil {
		return *contributions.WaitingTime
	}
	return v
}

type CreateTenantRequest struct {
	BuildingId  string  `json:"buildingId" validate:"required"`
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name" validate:"required"`
	SectionId   string  `json:"sectionId" validate:"required"`
}

func (createTenantRequest CreateTenantRequest) GetBuildingId() string {
	return createTenantRequest.BuildingId
}

func (createTenantRequest CreateTenantRequest) GetDescription() string {
	var v string
	if createTenantRequest.Description != nil {
		return *createTenantRequest.Description
	}
	return v
}

func (createTenantRequest CreateTenantRequest) GetName() string {
	return createTenantRequest.Name
}

func (createTenantRequest CreateTenantRequest) GetSectionId() string {
	return createTenantRequest.SectionId
}

type ExternalAPIConfig struct {
	AppointmentServicesHttpMethod       *string           `json:"appointmentServicesHttpMethod,omitempty"`
	AppointmentServicesLanguageHandling *string           `json:"appointmentServicesLanguageHandling,omitempty"`
	AppointmentServicesLanguageHeader   *string           `json:"appointmentServicesLanguageHeader,omitempty"`
	AppointmentServicesUrl              *string           `json:"appointmentServicesUrl,omitempty"`
	GenericServices                     []GenericService  `json:"genericServices,omitempty" validate:"dive"`
	GenericServicesHttpMethod           *string           `json:"genericServicesHttpMethod,omitempty"`
	GenericServicesLanguageHandling     *string           `json:"genericServicesLanguageHandling,omitempty"`
	GenericServicesLanguageHeader       *string           `json:"genericServicesLanguageHeader,omitempty"`
	GenericServicesUrl                  *string           `json:"genericServicesUrl,omitempty"`
	Headers                             map[string]string `json:"headers,omitempty"`
	MultilingualSupport                 *bool             `json:"multilingualSupport,omitempty"`
	RetryAttempts                       int64             `json:"retryAttempts"`
	SupportedLanguages                  []string          `json:"supportedLanguages,omitempty" validate:"dive"`
	TimeoutSeconds                      int64             `json:"timeoutSeconds"`
	UseDeepLTranslation                 *bool             `json:"useDeepLTranslation,omitempty"`
	WebhookHttpMethod                   *string           `json:"webhookHttpMethod,omitempty"`
	WebhookRetryAttempts                *int64            `json:"webhookRetryAttempts,omitempty"`
	WebhookTimeoutSeconds               *int64            `json:"webhookTimeoutSeconds,omitempty"`
	WebhookUrl                          *string           `json:"webhookUrl,omitempty"`
}

func (externalAPIConfig ExternalAPIConfig) GetAppointmentServicesHttpMethod() string {
	var v string
	if externalAPIConfig.AppointmentServicesHttpMethod != nil {
		return *externalAPIConfig.AppointmentServicesHttpMethod
	}
	return v
}

func (externalAPIConfig ExternalAPIConfig) GetAppointmentServicesLanguageHandling() string {
	var v string
	if externalAPIConfig.AppointmentServicesLanguageHandling != nil {
		return *externalAPIConfig.AppointmentServicesLanguageHandling
	}
	return v
}

func (externalAPIConfig ExternalAPIConfig) GetAppointmentServicesLanguageHeader() string {
	var v string
	if externalAPIConfig.AppointmentServicesLanguageHeader != nil {
		return *externalAPIConfig.AppointmentServicesLanguageHeader
	}
	return v
}

func (externalAPIConfig ExternalAPIConfig) GetAppointmentServicesUrl() string {
	var v string
	if externalAPIConfig.AppointmentServicesUrl != nil {
		return *externalAPIConfig.AppointmentServicesUrl
	}
	return v
}

func (externalAPIConfig ExternalAPIConfig) GetGenericServices() []GenericService {
	return externalAPIConfig.GenericServices
}

func (externalAPIConfig ExternalAPIConfig) GetGenericServicesHttpMethod() string {
	var v string
	if externalAPIConfig.GenericServicesHttpMethod != nil {
		return *externalAPIConfig.GenericServicesHttpMethod
	}
	return v
}

func (externalAPIConfig ExternalAPIConfig) GetGenericServicesLanguageHandling() string {
	var v string
	if externalAPIConfig.GenericServicesLanguageHandling != nil {
		return *externalAPIConfig.GenericServicesLanguageHandling
	}
	return v
}

func (externalAPIConfig ExternalAPIConfig) GetGenericServicesLanguageHeader() string {
	var v string
	if externalAPIConfig.GenericServicesLanguageHeader != nil {
		return *externalAPIConfig.GenericServicesLanguageHeader
	}
	return v
}

func (externalAPIConfig ExternalAPIConfig) GetGenericServicesUrl() string {
	var v string
	if externalAPIConfig.GenericServicesUrl != nil {
		return *externalAPIConfig.GenericServicesUrl
	}
	return v
}

func (externalAPIConfig ExternalAPIConfig) GetHeaders() map[string]string {
	return externalAPIConfig.Headers
}

func (externalAPIConfig ExternalAPIConfig) GetMultilingualSupport() bool {
	var v bool
	if externalAPIConfig.MultilingualSupport != nil {
		return *externalAPIConfig.MultilingualSupport
	}
	return v
}

func (externalAPIConfig ExternalAPIConfig) GetRetryAttempts() int64 {
	return externalAPIConfig.RetryAttempts
}

func (externalAPIConfig ExternalAPIConfig) GetSupportedLanguages() []string {
	return externalAPIConfig.SupportedLanguages
}

func (externalAPIConfig ExternalAPIConfig) GetTimeoutSeconds() int64 {
	return externalAPIConfig.TimeoutSeconds
}

func (externalAPIConfig ExternalAPIConfig) GetUseDeepLTranslation() bool {
	var v bool
	if externalAPIConfig.UseDeepLTranslation != nil {
		return *externalAPIConfig.UseDeepLTranslation
	}
	return v
}

func (externalAPIConfig ExternalAPIConfig) GetWebhookHttpMethod() string {
	var v string
	if externalAPIConfig.WebhookHttpMethod != nil {
		return *externalAPIConfig.WebhookHttpMethod
	}
	return v
}

func (externalAPIConfig ExternalAPIConfig) GetWebhookRetryAttempts() int64 {
	var v int64
	if externalAPIConfig.WebhookRetryAttempts != nil {
		return *externalAPIConfig.WebhookRetryAttempts
	}
	return v
}

func (externalAPIConfig ExternalAPIConfig) GetWebhookTimeoutSeconds() int64 {
	var v int64
	if externalAPIConfig.WebhookTimeoutSeconds != nil {
		return *externalAPIConfig.WebhookTimeoutSeconds
	}
	return v
}

func (externalAPIConfig ExternalAPIConfig) GetWebhookUrl() string {
	var v string
	if externalAPIConfig.WebhookUrl != nil {
		return *externalAPIConfig.WebhookUrl
	}
	return v
}

type FitnessConfig struct {
	Contributions *Contributions `json:"contributions" validate:"required"`
	Explanation   *string        `json:"explanation,omitempty"`
}

func (fitnessConfig FitnessConfig) GetContributions() Contributions {
	var v Contributions
	if fitnessConfig.Contributions != nil {
		return *fitnessConfig.Contributions
	}
	return v
}

func (fitnessConfig FitnessConfig) GetExplanation() string {
	var v string
	if fitnessConfig.Explanation != nil {
		return *fitnessConfig.Explanation
	}
	return v
}

type GenericService struct {
	Description *string `json:"description,omitempty"`
	Duration    *int64  `json:"duration,omitempty"`
	Enabled     bool    `json:"enabled"`
	Id          string  `json:"id" validate:"required"`
	Name        string  `json:"name" validate:"required"`
}

func (genericService GenericService) GetDescription() string {
	var v string
	if genericService.Description != nil {
		return *genericService.Description
	}
	return v
}

func (genericService GenericService) GetDuration() int64 {
	var v int64
	if genericService.Duration != nil {
		return *genericService.Duration
	}
	return v
}

func (genericService GenericService) GetEnabled() bool {
	return genericService.Enabled
}

func (genericService GenericService) GetId() string {
	return genericService.Id
}

func (genericService GenericService) GetName() string {
	return genericService.Name
}

type ManualOverride struct {
	Description *string `json:"description,omitempty"`
	Enabled     bool    `json:"enabled"`
	Weight      float64 `json:"weight"`
}

func (manualOverride ManualOverride) GetDescription() string {
	var v string
	if manualOverride.Description != nil {
		return *manualOverride.Description
	}
	return v
}

func (manualOverride ManualOverride) GetEnabled() bool {
	return manualOverride.Enabled
}

func (manualOverride ManualOverride) GetWeight() float64 {
	return manualOverride.Weight
}

type PriorityConfig struct {
	Description   *string        `json:"description,omitempty"`
	PriorityModel *PriorityModel `json:"priorityModel" validate:"required"`
	Version       string         `json:"version" validate:"required"`
}

func (priorityConfig PriorityConfig) GetDescription() string {
	var v string
	if priorityConfig.Description != nil {
		return *priorityConfig.Description
	}
	return v
}

func (priorityConfig PriorityConfig) GetPriorityModel() PriorityModel {
	var v PriorityModel
	if priorityConfig.PriorityModel != nil {
		return *priorityConfig.PriorityModel
	}
	return v
}

func (priorityConfig PriorityConfig) GetVersion() string {
	return priorityConfig.Version
}

type PriorityModel struct {
	Algorithm *Algorithm     `json:"algorithm,omitempty"`
	Fitness   *FitnessConfig `json:"fitness" validate:"required"`
	Tiers     []Tier         `json:"tiers" validate:"required,dive"`
}

func (priorityModel PriorityModel) GetAlgorithm() Algorithm {
	var v Algorithm
	if priorityModel.Algorithm != nil {
		return *priorityModel.Algorithm
	}
	return v
}

func (priorityModel PriorityModel) GetFitness() FitnessConfig {
	var v FitnessConfig
	if priorityModel.Fitness != nil {
		return *priorityModel.Fitness
	}
	return v
}

func (priorityModel PriorityModel) GetTiers() []Tier {
	return priorityModel.Tiers
}

type RestartResponse struct {
	Message string `json:"message" validate:"required"`
	Success bool   `json:"success"`
}

func (restartResponse RestartResponse) GetMessage() string {
	return restartResponse.Message
}

func (restartResponse RestartResponse) GetSuccess() bool {
	return restartResponse.Success
}

type RoomConfig struct {
	Description   *string              `json:"description,omitempty"`
	Id            string               `json:"id" validate:"required"`
	IsDefault     bool                 `json:"isDefault"`
	Name          string               `json:"name" validate:"required"`
	ServicePoints []ServicePointConfig `json:"servicePoints" validate:"required,dive"`
}

func (roomConfig RoomConfig) GetDescription() string {
	var v string
	if roomConfig.Description != nil {
		return *roomConfig.Description
	}
	return v
}

func (roomConfig RoomConfig) GetId() string {
	return roomConfig.Id
}

func (roomConfig RoomConfig) GetIsDefault() bool {
	return roomConfig.IsDefault
}

func (roomConfig RoomConfig) GetName() string {
	return roomConfig.Name
}

func (roomConfig RoomConfig) GetServicePoints() []ServicePointConfig {
	return roomConfig.ServicePoints
}

type ServicePointConfig struct {
	Description *string `json:"description,omitempty"`
	Id          string  `json:"id" validate:"required"`
	ManagerId   *string `json:"managerId,omitempty"`
	ManagerName *string `json:"managerName,omitempty"`
	Name        string  `json:"name" validate:"required"`
}

func (servicePointConfig ServicePointConfig) GetDescription() string {
	var v string
	if servicePointConfig.Description != nil {
		return *servicePointConfig.Description
	}
	return v
}

func (servicePointConfig ServicePointConfig) GetId() string {
	return servicePointConfig.Id
}

func (servicePointConfig ServicePointConfig) GetManagerId() string {
	var v string
	if servicePointConfig.ManagerId != nil {
		return *servicePointConfig.ManagerId
	}
	return v
}

func (servicePointConfig ServicePointConfig) GetManagerName() string {
	var v string
	if servicePointConfig.ManagerName != nil {
		return *servicePointConfig.ManagerName
	}
	return v
}

func (servicePointConfig ServicePointConfig) GetName() string {
	return servicePointConfig.Name
}

type SymbolWeights struct {
	Description *string            `json:"description,omitempty"`
	Values      map[string]float64 `json:"values,omitempty"`
}

func (symbolWeights SymbolWeights) GetDescription() string {
	var v string
	if symbolWeights.Description != nil {
		return *symbolWeights.Description
	}
	return v
}

func (symbolWeights SymbolWeights) GetValues() map[string]float64 {
	return symbolWeights.Values
}

type SystemConfiguration struct {
	AllowWildcard bool               `json:"allowWildcard"`
	CreatedAt     *time.Time         `json:"createdAt,omitempty"`
	DefaultRoom   string             `json:"defaultRoom" validate:"required"`
	ExternalAPI   *ExternalAPIConfig `json:"externalAPI" validate:"required"`
	Id            *string            `json:"id,omitempty"`
	Rooms         []RoomConfig       `json:"rooms" validate:"required,dive"`
	UpdatedAt     *time.Time         `json:"updatedAt,omitempty"`
	WebSocketPath string             `json:"webSocketPath" validate:"required"`
}

func (systemConfiguration SystemConfiguration) GetAllowWildcard() bool {
	return systemConfiguration.AllowWildcard
}

func (systemConfiguration SystemConfiguration) GetCreatedAt() time.Time {
	var v time.Time
	if systemConfiguration.CreatedAt != nil {
		return *systemConfiguration.CreatedAt
	}
	return v
}

func (systemConfiguration SystemConfiguration) GetDefaultRoom() string {
	return systemConfiguration.DefaultRoom
}

func (systemConfiguration SystemConfiguration) GetExternalAPI() ExternalAPIConfig {
	var v ExternalAPIConfig
	if systemConfiguration.ExternalAPI != nil {
		return *systemConfiguration.ExternalAPI
	}
	return v
}

func (systemConfiguration SystemConfiguration) GetId() string {
	var v string
	if systemConfiguration.Id != nil {
		return *systemConfiguration.Id
	}
	return v
}

func (systemConfiguration SystemConfiguration) GetRooms() []RoomConfig {
	return systemConfiguration.Rooms
}

func (systemConfiguration SystemConfiguration) GetUpdatedAt() time.Time {
	var v time.Time
	if systemConfiguration.UpdatedAt != nil {
		return *systemConfiguration.UpdatedAt
	}
	return v
}

func (systemConfiguration SystemConfiguration) GetWebSocketPath() string {
	return systemConfiguration.WebSocketPath
}

type Tenant struct {
	BuildingId  string     `json:"buildingId" validate:"required"`
	CreatedAt   *time.Time `json:"createdAt,omitempty"`
	Description *string    `json:"description,omitempty"`
	Id          *string    `json:"id,omitempty"`
	Name        string     `json:"name" validate:"required"`
	SectionId   string     `json:"sectionId" validate:"required"`
	UpdatedAt   *time.Time `json:"updatedAt,omitempty"`
}

func (tenant Tenant) GetBuildingId() string {
	return tenant.BuildingId
}

func (tenant Tenant) GetCreatedAt() time.Time {
	var v time.Time
	if tenant.CreatedAt != nil {
		return *tenant.CreatedAt
	}
	return v
}

func (tenant Tenant) GetDescription() string {
	var v string
	if tenant.Description != nil {
		return *tenant.Description
	}
	return v
}

func (tenant Tenant) GetId() string {
	var v string
	if tenant.Id != nil {
		return *tenant.Id
	}
	return v
}

func (tenant Tenant) GetName() string {
	return tenant.Name
}

func (tenant Tenant) GetSectionId() string {
	return tenant.SectionId
}

func (tenant Tenant) GetUpdatedAt() time.Time {
	var v time.Time
	if tenant.UpdatedAt != nil {
		return *tenant.UpdatedAt
	}
	return v
}

type Tier struct {
	Condition   *TierCondition `json:"condition,omitempty"`
	Description *string        `json:"description,omitempty"`
	Id          int64          `json:"id"`
	Name        string         `json:"name" validate:"required"`
}

func (tier Tier) GetCondition() TierCondition {
	var v TierCondition
	if tier.Condition != nil {
		return *tier.Condition
	}
	return v
}

func (tier Tier) GetDescription() string {
	var v string
	if tier.Description != nil {
		return *tier.Description
	}
	return v
}

func (tier Tier) GetId() int64 {
	return tier.Id
}

func (tier Tier) GetName() string {
	return tier.Name
}

type TierCondition struct {
	SymbolsAnyOf    []string `json:"symbolsAnyOf,omitempty" validate:"dive"`
	SymbolsNotAnyOf []string `json:"symbolsNotAnyOf,omitempty" validate:"dive"`
}

func (tierCondition TierCondition) GetSymbolsAnyOf() []string {
	return tierCondition.SymbolsAnyOf
}

func (tierCondition TierCondition) GetSymbolsNotAnyOf() []string {
	return tierCondition.SymbolsNotAnyOf
}

type TranslationCacheStats struct {
	Api_calls_saved *int64  `json:"api_calls_saved,omitempty"`
	Cache_size      *int64  `json:"cache_size,omitempty"`
	Expiration_time *string `json:"expiration_time,omitempty"`
	Hit_rate        *string `json:"hit_rate,omitempty"`
	Hits            *int64  `json:"hits,omitempty"`
	Max_cache_size  *int64  `json:"max_cache_size,omitempty"`
	Misses          *int64  `json:"misses,omitempty"`
	Total_requests  *int64  `json:"total_requests,omitempty"`
}

func (translationCacheStats TranslationCacheStats) GetApi_calls_saved() int64 {
	var v int64
	if translationCacheStats.Api_calls_saved != nil {
		return *translationCacheStats.Api_calls_saved
	}
	return v
}

func (translationCacheStats TranslationCacheStats) GetCache_size() int64 {
	var v int64
	if translationCacheStats.Cache_size != nil {
		return *translationCacheStats.Cache_size
	}
	return v
}

func (translationCacheStats TranslationCacheStats) GetExpiration_time() string {
	var v string
	if translationCacheStats.Expiration_time != nil {
		return *translationCacheStats.Expiration_time
	}
	return v
}

func (translationCacheStats TranslationCacheStats) GetHit_rate() string {
	var v string
	if translationCacheStats.Hit_rate != nil {
		return *translationCacheStats.Hit_rate
	}
	return v
}

func (translationCacheStats TranslationCacheStats) GetHits() int64 {
	var v int64
	if translationCacheStats.Hits != nil {
		return *translationCacheStats.Hits
	}
	return v
}

func (translationCacheStats TranslationCacheStats) GetMax_cache_size() int64 {
	var v int64
	if translationCacheStats.Max_cache_size != nil {
		return *translationCacheStats.Max_cache_size
	}
	return v
}

func (translationCacheStats TranslationCacheStats) GetMisses() int64 {
	var v int64
	if translationCacheStats.Misses != nil {
		return *translationCacheStats.Misses
	}
	return v
}

func (translationCacheStats TranslationCacheStats) GetTotal_requests() int64 {
	var v int64
	if translationCacheStats.Total_requests != nil {
		return *translationCacheStats.Total_requests
	}
	return v
}

type WaitingTime struct {
	Description     *string `json:"description,omitempty"`
	WeightPerMinute float64 `json:"weightPerMinute"`
}

func (waitingTime WaitingTime) GetDescription() string {
	var v string
	if waitingTime.Description != nil {
		return *waitingTime.Description
	}
	return v
}

func (waitingTime WaitingTime) GetWeightPerMinute() float64 {
	return waitingTime.WeightPerMinute
}
