// Code generated by go generate; DO NOT EDIT.
package dto

type JoinResult struct {
	EntryID      string `json:"entryID" validate:"required"`
	QrUrl        string `json:"qrUrl" validate:"required"`
	TicketNumber string `json:"ticketNumber" validate:"required"`
}

func (joinResult JoinResult) GetEntryID() string {
	return joinResult.EntryID
}

func (joinResult JoinResult) GetQrUrl() string {
	return joinResult.QrUrl
}

func (joinResult JoinResult) GetTicketNumber() string {
	return joinResult.TicketNumber
}

type SwipeRequest struct {
	IdCardRaw *string `json:"idCardRaw,omitempty"`
}

func (swipeRequest SwipeRequest) GetIdCardRaw() string {
	var v string
	if swipeRequest.IdCardRaw != nil {
		return *swipeRequest.IdCardRaw
	}
	return v
}
