// Code generated by go generate; DO NOT EDIT.
package dto

type JoinResult struct {
	EntryId      string `json:"entryId" validate:"required"`
	QrUrl        string `json:"qrUrl" validate:"required"`
	TicketNumber string `json:"ticketNumber" validate:"required"`
}

func (joinResult JoinResult) GetEntryId() string {
	return joinResult.EntryId
}

func (joinResult JoinResult) GetQrUrl() string {
	return joinResult.QrUrl
}

func (joinResult JoinResult) GetTicketNumber() string {
	return joinResult.TicketNumber
}

type SwipeRequest struct {
	IdCardRaw string `json:"idCardRaw" validate:"required"`
}

func (swipeRequest SwipeRequest) GetIdCardRaw() string {
	return swipeRequest.IdCardRaw
}
