// Code generated by go generate; DO NOT EDIT.
// MANUAL MODIFICATION: AppointmentTime changed to *FlexibleTime to support multiple datetime formats
package dto

import "time"

type PatientInformation struct {
	Age             *int64        `json:"age,omitempty"`
	AppointmentTime *FlexibleTime `json:"appointmentTime,omitempty"`
	ManualOverride  *float64      `json:"manualOverride,omitempty"`
	Symbols         []string      `json:"symbols,omitempty" validate:"dive"`
}

func (patientInformation PatientInformation) GetAge() int64 {
	var v int64
	if patientInformation.Age != nil {
		return *patientInformation.Age
	}
	return v
}

func (patientInformation PatientInformation) GetAppointmentTime() time.Time {
	var v time.Time
	if patientInformation.AppointmentTime != nil {
		return patientInformation.AppointmentTime.Time
	}
	return v
}

// GetAppointmentTimePtr returns the appointment time as *time.Time for compatibility with queue service
func (patientInformation PatientInformation) GetAppointmentTimePtr() *time.Time {
	if patientInformation.AppointmentTime != nil {
		return patientInformation.AppointmentTime.ToTimePtr()
	}
	return nil
}

func (patientInformation PatientInformation) GetManualOverride() float64 {
	var v float64
	if patientInformation.ManualOverride != nil {
		return *patientInformation.ManualOverride
	}
	return v
}

func (patientInformation PatientInformation) GetSymbols() []string {
	return patientInformation.Symbols
}
