// Code generated by go generate; DO NOT EDIT.
// MANUAL OVERRIDE: Using FlexibleTime for AppointmentTime to support multiple date formats
package dto

type PatientInformation struct {
	Age             *int64        `json:"age,omitempty"`
	AppointmentTime *FlexibleTime `json:"appointmentTime,omitempty"`
	ManualOverride  *float64      `json:"manualOverride,omitempty"`
	Symbols         []string      `json:"symbols,omitempty" validate:"dive"`
}

func (patientInformation PatientInformation) GetAge() int64 {
	var v int64
	if patientInformation.Age != nil {
		return *patientInformation.Age
	}
	return v
}

func (patientInformation PatientInformation) GetAppointmentTime() FlexibleTime {
	var v FlexibleTime
	if patientInformation.AppointmentTime != nil {
		return *patientInformation.AppointmentTime
	}
	return v
}

// GetAppointmentTimePtr returns the appointment time as a *time.Time for compatibility
func (patientInformation PatientInformation) GetAppointmentTimePtr() *FlexibleTime {
	return patientInformation.AppointmentTime
}

func (patientInformation PatientInformation) GetManualOverride() float64 {
	var v float64
	if patientInformation.ManualOverride != nil {
		return *patientInformation.ManualOverride
	}
	return v
}

func (patientInformation PatientInformation) GetSymbols() []string {
	return patientInformation.Symbols
}
