// Code generated by go generate; DO NOT EDIT.
// MANUAL MODIFICATION: Added AppointmentTime and CreatedAt fields for frontend display
package dto

import (
	"time"

	"github.com/arfis/waiting-room/internal/data/dto/queueentrystatus"
)

type MarkInRoomRequest struct {
	EntryID string `json:"entryID" validate:"required"`
}

func (markInRoomRequest MarkInRoomRequest) GetEntryID() string {
	return markInRoomRequest.EntryID
}

type PublicEntry struct {
	CanCancel    bool                              `json:"canCancel"`
	EntryID      string                            `json:"entryID" validate:"required"`
	EtaMinutes   int64                             `json:"etaMinutes"`
	Position     int64                             `json:"position"`
	Status       queueentrystatus.QueueEntryStatus `json:"status" validate:"required"`
	TicketNumber string                            `json:"ticketNumber" validate:"required"`
}

func (publicEntry PublicEntry) GetCanCancel() bool {
	return publicEntry.CanCancel
}

func (publicEntry PublicEntry) GetEntryID() string {
	return publicEntry.EntryID
}

func (publicEntry PublicEntry) GetEtaMinutes() int64 {
	return publicEntry.EtaMinutes
}

func (publicEntry PublicEntry) GetPosition() int64 {
	return publicEntry.Position
}

func (publicEntry PublicEntry) GetStatus() queueentrystatus.QueueEntryStatus {
	return publicEntry.Status
}

func (publicEntry PublicEntry) GetTicketNumber() string {
	return publicEntry.TicketNumber
}

type QueueEntry struct {
	ID              string                            `json:"ID" validate:"required"`
	Age             *int64                            `json:"age,omitempty"`
	AppointmentTime *time.Time                        `json:"appointmentTime,omitempty"`
	CreatedAt       *time.Time                        `json:"createdAt,omitempty"`
	Position        int64                             `json:"position"`
	ServiceDuration *int64                            `json:"serviceDuration,omitempty"`
	ServiceName     *string                           `json:"serviceName,omitempty"`
	ServicePoint    *string                           `json:"servicePoint,omitempty"`
	Status          queueentrystatus.QueueEntryStatus `json:"status" validate:"required"`
	Symbols         []string                          `json:"symbols,omitempty" validate:"dive"`
	TicketNumber    string                            `json:"ticketNumber" validate:"required"`
	WaitingRoomID   string                            `json:"waitingRoomID" validate:"required"`
}

func (queueEntry QueueEntry) GetID() string {
	return queueEntry.ID
}

func (queueEntry QueueEntry) GetAge() int64 {
	var v int64
	if queueEntry.Age != nil {
		return *queueEntry.Age
	}
	return v
}

func (queueEntry QueueEntry) GetPosition() int64 {
	return queueEntry.Position
}

func (queueEntry QueueEntry) GetServiceDuration() int64 {
	var v int64
	if queueEntry.ServiceDuration != nil {
		return *queueEntry.ServiceDuration
	}
	return v
}

func (queueEntry QueueEntry) GetServiceName() string {
	var v string
	if queueEntry.ServiceName != nil {
		return *queueEntry.ServiceName
	}
	return v
}

func (queueEntry QueueEntry) GetServicePoint() string {
	var v string
	if queueEntry.ServicePoint != nil {
		return *queueEntry.ServicePoint
	}
	return v
}

func (queueEntry QueueEntry) GetStatus() queueentrystatus.QueueEntryStatus {
	return queueEntry.Status
}

func (queueEntry QueueEntry) GetSymbols() []string {
	return queueEntry.Symbols
}

func (queueEntry QueueEntry) GetTicketNumber() string {
	return queueEntry.TicketNumber
}

func (queueEntry QueueEntry) GetWaitingRoomID() string {
	return queueEntry.WaitingRoomID
}

type ServicePoint struct {
	ID          string  `json:"ID" validate:"required"`
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name" validate:"required"`
}

func (servicePoint ServicePoint) GetID() string {
	return servicePoint.ID
}

func (servicePoint ServicePoint) GetDescription() string {
	var v string
	if servicePoint.Description != nil {
		return *servicePoint.Description
	}
	return v
}

func (servicePoint ServicePoint) GetName() string {
	return servicePoint.Name
}
