// Code generated by go generate; DO NOT EDIT.

package dto

import "time"

type ManagerLoginRequest struct {
	RoomID         string `json:"roomID" validate:"required"`
	ServicePointID string `json:"servicePointID" validate:"required"`
}

func (managerLoginRequest ManagerLoginRequest) GetRoomID() string {
	return managerLoginRequest.RoomID
}

func (managerLoginRequest ManagerLoginRequest) GetServicePointID() string {
	return managerLoginRequest.ServicePointID
}

type ManagerStatus struct {
	IsAvailable    bool      `json:"isAvailable"`
	LastSeen       time.Time `json:"lastSeen" validate:"required"`
	ManagerID      string    `json:"managerID" validate:"required"`
	ManagerName    string    `json:"managerName" validate:"required"`
	RoomID         string    `json:"roomID" validate:"required"`
	ServicePointID string    `json:"servicePointID" validate:"required"`
}

func (managerStatus ManagerStatus) GetIsAvailable() bool {
	return managerStatus.IsAvailable
}

func (managerStatus ManagerStatus) GetLastSeen() time.Time {
	return managerStatus.LastSeen
}

func (managerStatus ManagerStatus) GetManagerID() string {
	return managerStatus.ManagerID
}

func (managerStatus ManagerStatus) GetManagerName() string {
	return managerStatus.ManagerName
}

func (managerStatus ManagerStatus) GetRoomID() string {
	return managerStatus.RoomID
}

func (managerStatus ManagerStatus) GetServicePointID() string {
	return managerStatus.ServicePointID
}
