// Code generated by go generate; DO NOT EDIT.
package dto

import "time"

type ManagerLoginRequest struct {
	RoomId         string `json:"roomId" validate:"required"`
	ServicePointId string `json:"servicePointId" validate:"required"`
}

func (managerLoginRequest ManagerLoginRequest) GetRoomId() string {
	return managerLoginRequest.RoomId
}

func (managerLoginRequest ManagerLoginRequest) GetServicePointId() string {
	return managerLoginRequest.ServicePointId
}

type ManagerStatus struct {
	IsAvailable    bool      `json:"isAvailable"`
	LastSeen       time.Time `json:"lastSeen" validate:"required"`
	ManagerId      string    `json:"managerId" validate:"required"`
	ManagerName    string    `json:"managerName" validate:"required"`
	RoomId         string    `json:"roomId" validate:"required"`
	ServicePointId string    `json:"servicePointId" validate:"required"`
}

func (managerStatus ManagerStatus) GetIsAvailable() bool {
	return managerStatus.IsAvailable
}

func (managerStatus ManagerStatus) GetLastSeen() time.Time {
	return managerStatus.LastSeen
}

func (managerStatus ManagerStatus) GetManagerId() string {
	return managerStatus.ManagerId
}

func (managerStatus ManagerStatus) GetManagerName() string {
	return managerStatus.ManagerName
}

func (managerStatus ManagerStatus) GetRoomId() string {
	return managerStatus.RoomId
}

func (managerStatus ManagerStatus) GetServicePointId() string {
	return managerStatus.ServicePointId
}
