// Code generated by go generate; DO NOT EDIT.
// Generator version: v3.0.1
package service

import (
	"context"
	nghisContext "github.com/arfis/waiting-room/nghis-adapter/internal/context"
	"strings"
)

const system = "system"

func GetSortString(sort []string) string {
	return strings.Join(sort, ", ")
}

// GetLogin returns user login from context or "system" if no login was found
func GetLogin(ctx context.Context) string {
	login := ctx.Value(nghisContext.LOGIN)
	if login == nil {
		return system
	}
	return login.(string)
}

// GetTenant returns tenant from context
func GetTenant(ctx context.Context) int32 {
	tenant := ctx.Value(nghisContext.TENANT)
	if tenant == nil {
		return 0
	}
	return tenant.(int32)
}
