// Code generated by go generate; DO NOT EDIT.
// Generator version: v3.3.2
//
// Package internal contains generated building blocks (DTOs, REST handlers, middleware,
// clients, errors and utilities) produced by service-gen based on the OpenAPI definition.
//
// Generated files (auto-detected):
//
//   - internal/client/authorization.go (1.1KB)
//   - internal/client/logger.go (2.0KB)
//   - internal/context/context.go (646B)
//   - internal/data/dto/appointment.go (740B)
//   - internal/data/dto/page.go (786B)
//   - internal/data/dto/service.go (909B)
//   - internal/errors/codes.go (695B)
//   - internal/errors/error.go (2.5KB)
//   - internal/errors/errorwithstack.go (5.3KB)
//   - internal/errors/response.go (1.3KB)
//   - internal/errors/response_write_error.go (1.0KB)
//   - internal/middleware/authorization.go (5.2KB)
//   - internal/middleware/cors.go (541B)
//   - internal/middleware/logging.go (2.2KB)
//   - internal/middleware/paging.go (1.8KB)
//   - internal/middleware/requestId.go (801B)
//   - internal/rest/handler/appointment/generated.go (1.4KB)
//   - internal/rest/handler/service/generated.go (1.8KB)
//   - internal/rest/handler/utils.go (7.6KB)
//   - internal/rest/register/generated.go (659B)
//   - internal/service/utils.go (1.1KB)
//   - internal/utils/ptr/ptr.go (336B)
//
// Summary: 22 files generated (40.2KB)
//
// The code is intended as an implementation scaffold. You can copy pieces out or extend
// them, but avoid manual edits inside generated sections (they may be overwritten on the
// next run). To prevent regeneration of a specific file, remove the auto-generated header.
package internal
