// Code generated by go generate; DO NOT EDIT.
package middleware

import (
	"context"
	"net/http"

	appCtx "github.com/arfis/waiting-room/internal/context"
	"github.com/google/uuid"
)

const (
	requestIdHeader     = "X-Request-Id"
	correlationIdHeader = "X-Correlation-Id"
)

func RequestIdMiddleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		var requestID string

		if requestID = r.Header.Get(requestIdHeader); requestID == "" {
			requestID = r.Header.Get(correlationIdHeader)
		}

		if err := uuid.Validate(requestID); err != nil {
			requestID = uuid.NewString()
		}

		r.Header.Set(requestIdHeader, requestID)

		next.ServeHTTP(w, r.WithContext(context.WithValue(r.Context(), appCtx.REQUESTID, requestID)))
	})
}
