// Code generated by go generate; DO NOT EDIT.
// Generator version: v3.0.1
package ptr

func Ptr[T any](val T) *T {
	return &val
}

func IsNil[T any](data *T) bool {
	return data == nil
}

func IsNotNil[T any](data *T) bool {
	return !IsNil(data)
}

func ValueDefault[T any](data *T, defaultValue T) T {
	if data == nil {
		return defaultValue
	}
	return *data
}
