// Code generated by go generate; DO NOT EDIT.

package dto

import "time"

type AppointmentResp struct {
	Duration      int64     `json:"duration"`
	Id            string    `json:"id" validate:"required"`
	RequestedTime time.Time `json:"requestedTime" validate:"required"`
	ServiceName   string    `json:"serviceName" validate:"required"`
}

func (appointmentResp AppointmentResp) GetDuration() int64 {
	return appointmentResp.Duration
}

func (appointmentResp AppointmentResp) GetId() string {
	return appointmentResp.Id
}

func (appointmentResp AppointmentResp) GetRequestedTime() time.Time {
	return appointmentResp.RequestedTime
}

func (appointmentResp AppointmentResp) GetServiceName() string {
	return appointmentResp.ServiceName
}
