// Code generated by go generate; DO NOT EDIT.
// Generator version: v3.0.1
package dto

import "time"

type AppointmentResp struct {
	Duration      int64     `json:"duration"`
	RequestedTime time.Time `json:"requestedTime" validate:"required"`
	ServiceName   string    `json:"serviceName" validate:"required"`
}

func (appointmentResp AppointmentResp) GetDuration() int64 {
	return appointmentResp.Duration
}

func (appointmentResp AppointmentResp) GetRequestedTime() time.Time {
	return appointmentResp.RequestedTime
}

func (appointmentResp AppointmentResp) GetServiceName() string {
	return appointmentResp.ServiceName
}
