// Code generated by go generate; DO NOT EDIT.
// Generator version: v3.0.1
package dto

type Page struct {
	Content          interface{} `json:"content"`
	Pageable         Pageable    `json:"pageable"`
	Empty            bool        `json:"empty"`
	First            bool        `json:"first"`
	Last             bool        `json:"last"`
	NumberOfElements int32       `json:"numberOfElements"`
	Size             int32       `json:"size"`
	TotalElements    int64       `json:"totalElements"`
	TotalPages       int32       `json:"totalPages"`
	Sort             Sort        `json:"sort"`
}

type Pageable struct {
	Page   int32 `json:"page"`
	Size   int32 `json:"size"`
	Offset int32 `json:"offset"`
}

type Sort struct {
	Empty    bool `json:"empty"`
	Sorted   bool `json:"sorted"`
	Unsorted bool `json:"unsorted"`
}
