// Code generated by go generate; DO NOT EDIT.

package dto

type FindServicesReq struct {
	Limit      int32   `json:"limit"`
	OrgUnitIDs []int64 `json:"orgUnitIDs" validate:"required,dive"`
}

func (findServicesReq FindServicesReq) GetLimit() int32 {
	return findServicesReq.Limit
}

func (findServicesReq FindServicesReq) GetOrgUnitIDs() []int64 {
	return findServicesReq.OrgUnitIDs
}

type ServicesResp struct {
	Code     string `json:"code" validate:"required"`
	Duration int64  `json:"duration"`
	Id       int64  `json:"id"`
	Name     string `json:"name" validate:"required"`
}

func (servicesResp ServicesResp) GetCode() string {
	return servicesResp.Code
}

func (servicesResp ServicesResp) GetDuration() int64 {
	return servicesResp.Duration
}

func (servicesResp ServicesResp) GetId() int64 {
	return servicesResp.Id
}

func (servicesResp ServicesResp) GetName() string {
	return servicesResp.Name
}
