// Code generated by go generate; DO NOT EDIT.
// Generator version: v3.0.1
package register

import (
	"github.com/arfis/waiting-room/nghis-adapter/internal/rest/handler/appointment"
	"github.com/go-chi/chi/v5"
	"go.uber.org/dig"
)

func Generated(r chi.Router, diContainer *dig.Container) {
	err := diContainer.Invoke(func(
		appointmentHandler *appointment.Handler,
	) error {
		r.Get("/patient/{nationalID}/appointments", appointmentHandler.GetAppointmentsForPatient)
		return nil
	})
	if err != nil {
		panic(err)
	}
}
