// Code generated by go generate; DO NOT EDIT.
package service

import (
	"context"
	appContext "github.com/arfis/waiting-room/internal/context"
)

const system = "system"

// GetLogin returns user userID from context or "system" if no userID was found
func GetUserID(ctx context.Context) string {
	userID := ctx.Value(appContext.USER_ID)
	if userID == nil {
		return system
	}
	return userID.(string)
}

// GetCompany returns company from context when available
func GetCompany(ctx context.Context) string {
	company := ctx.Value(appContext.COMPANY)
	if company == nil {
		return ""
	}
	return company.(string)
}
