// Code generated by go generate; DO NOT EDIT.
package service

import (
	"context"
	appContext "github.com/arfis/waiting-room/internal/context"
	"github.com/arfis/waiting-room/internal/middleware"
)

const system = "system"

// GetLogin returns user userID from context or "system" if no userID was found
func GetUserID(ctx context.Context) string {
	userID := ctx.Value(appContext.USER_ID)
	if userID == nil {
		return system
	}
	return userID.(string)
}

// GetCompany returns company from context when available
func GetCompany(ctx context.Context) string {
	company := ctx.Value(appContext.COMPANY)
	if company == nil {
		return ""
	}
	return company.(string)
}

// GetTenantID returns tenant ID from context when available
func GetTenantID(ctx context.Context) string {
	tenantID := ctx.Value(middleware.TENANT)
	if tenantID == nil {
		return ""
	}
	return tenantID.(string)
}
