// Code generated by go generate; DO NOT EDIT.
// Generator version: v3.3.1
//
// Package internal contains generated building blocks (DTOs, REST handlers, middleware,
// clients, errors and utilities) produced by service-gen based on the OpenAPI definition.
//
// Generated files (auto-detected):
//
//   - .golangci.yaml (1.9KB)
//   - internal/client/authorization.go (1.1KB)
//   - internal/client/logger.go (2.0KB)
//   - internal/context/context.go (646B)
//   - internal/data/dto/admin.go (16.2KB)
//   - internal/data/dto/configuration.go (2.6KB)
//   - internal/data/dto/kiosk.go (2.0KB)
//   - internal/data/dto/page.go (786B)
//   - internal/data/dto/queue.go (3.4KB)
//   - internal/data/dto/queueentrystatus/queueentrystatus.go (1.3KB)
//   - internal/data/dto/servicepoint.go (1.4KB)
//   - internal/errors/codes.go (695B)
//   - internal/errors/error.go (2.5KB)
//   - internal/errors/errorwithstack.go (5.3KB)
//   - internal/errors/generated.go (1.0KB)
//   - internal/errors/response.go (1.2KB)
//   - internal/middleware/cors.go (541B)
//   - internal/middleware/logging.go (2.2KB)
//   - internal/middleware/paging.go (1.8KB)
//   - internal/middleware/requestId.go (787B)
//   - internal/rest/handler/admin/generated.go (9.9KB)
//   - internal/rest/handler/configuration/generated.go (1.2KB)
//   - internal/rest/handler/kiosk/generated.go (3.9KB)
//   - internal/rest/handler/queue/generated.go (5.7KB)
//   - internal/rest/handler/servicepoint/generated.go (3.2KB)
//   - internal/rest/handler/utils.go (7.4KB)
//   - internal/rest/register/generated.go (3.2KB)
//   - internal/service/utils.go (1.1KB)
//   - internal/utils/ptr/ptr.go (336B)
//
// Summary: 29 files generated (85.0KB)
//
// The code is intended as an implementation scaffold. You can copy pieces out or extend
// them, but avoid manual edits inside generated sections (they may be overwritten on the
// next run). To prevent regeneration of a specific file, remove the auto-generated header.
package internal
