// Code generated by go generate; DO NOT EDIT.
// Generator version: v3.0.1
package context

import "context"

type NGHIS_CONTEXT string

var (
	TENANT         NGHIS_CONTEXT = "TENANT"
	LOGIN          NGHIS_CONTEXT = "LOGIN"
	REQUESTID      NGHIS_CONTEXT = "REQUEST_ID"
	SUB            NGHIS_CONTEXT = "SUB"
	USERNAME       NGHIS_CONTEXT = "USERNAME"
	ORIGINAL_TOKEN NGHIS_CONTEXT = "ORIGINAL_TOKEN"

	CLIENT_NAME string = "CLIENT_NAME"
	CLIENT_OP   string = "CLIENT_OP"
)

// NewApplicationContext prepares main application context with cancel function
func NewApplicationContext() (context.Context, context.CancelFunc) {
	return context.WithCancel(context.Background())
}
