package middleware

import (
	"fmt"
	"gitlab.com/soluqa/bookio/service-generator/internal/utils"
)

func generateCors(wd string) {
	cors := utils.ExecuteAndFormat(corsT, nil)
	utils.ForceSave(fmt.Sprintf("%s/internal/middleware/cors.go", wd), cors)
}

var corsT = utils.CreateTemplate(`
// Code generated by go generate; DO NOT EDIT.
package middleware

import (
	"net/http"
	"time"

	"github.com/go-chi/cors"
)

func Cors() func(next http.Handler) http.Handler {
	return cors.Handler(cors.Options{
		AllowedOrigins:   []string{"*"},
		AllowedMethods:   []string{"GET", "POST", "PUT", "DELETE", "OPTIONS"},
		AllowedHeaders:   []string{"Accept", "Authorization", "Content-Type", "X-CSRF-Token", "Origin"},
		ExposedHeaders:   []string{"Content-Length"},
		AllowCredentials: true,
		MaxAge:           int(12 * time.Hour),
	})
}
`)
