package linter

import (
	"fmt"

	"gitlab.com/soluqa/bookio/service-generator/internal/utils"
)

func Generate(wd string) {
	code := utils.Execute(linter, nil)
	utils.ForceSavePlainOrSkip(fmt.Sprintf("%s/.golangci.yaml", wd), code)
}

var linter = utils.CreateTemplate(`# Code generated by go generate; DO NOT EDIT.
run:
  timeout: 5m
  concurrency: 4
  tests: true

# all available settings of specific linters
linters-settings:
  errcheck:
    # report about not checking of errors in type assetions
    check-type-assertions: true
    # report about assignment of errors to blank identifier
    check-blank: true
  errorlint:
    errorf: true
  govet:
    # report about shadowed variables
    enable:
      - shadow
  gocyclo:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 15
  lll:
    # max line length, lines longer will be reported. Default is 120.
    # '\t' is counted as 1 character by default, and can be changed with the tab-width option
    line-length: 200  
  unparam:
    # Inspect exported functions, default is false. Set to true if no external program/library imports your code.
    check-exported: true
  nakedret:
    # make an issue if func has more lines of code than this setting and it has naked returns
    max-func-lines: 60
  prealloc:
    # Report preallocation suggestions only on simple loops that have no returns/breaks/continues/gotos in them.
    simple: true
    range-loops: true # Report preallocation suggestions on range loops
    for-loops: false # Report preallocation suggestions on for loops
  gosec:
    excludes:
      - G601  # Implicit memory aliasing in for loop. (applicable only for <= go1.21)
linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - errorlint
    - ineffassign
    - typecheck
    - revive
    - unconvert
    - goconst
    - gocyclo
    - staticcheck
    - unused
    - gosimple
    - dupl
    - gofmt
    - gosec
    - lll
    - gocritic
    - predeclared
    - thelper
    - makezero
    - paralleltest
  fast: false
issues:
  exclude-rules:
    - text: 'shadow: declaration of "err" shadows declaration at'
      linters: [ govet ] 
    - text: 'var-naming:'
      linters: [ revive ]
      path: 'internal/data/dto'  
`)
