# Production configuration for Waiting Room System

server:
  port: 8080
  host: "0.0.0.0"  # Listen on all interfaces
  
database:
  mongodb:
    uri: "mongodb://admin:admin@mongodb:27017/waiting_room?authSource=admin"
    database: "waiting_room"
    
deepl:
  api_key: "1937e097"
  
cors:
  allowed_origins:
    - "https://yourdomain.com"  # Replace with your actual domain
    - "https://kiosk.yourdomain.com"
    - "https://backoffice.yourdomain.com"
    - "https://tv.yourdomain.com"
    - "https://mobile.yourdomain.com"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allowed_headers:
    - "Content-Type"
    - "Authorization"
    - "X-Requested-With"

websocket:
  enabled: true
  path: "/ws/queue"

rooms:
  default_room: "triage-1"  # Default room for production
  allow_wildcard: false     # Restrict to configured rooms in production
  rooms:
    - id: "triage-1"
      name: "Triage Room"
      service_points:
        - id: "window-1"
          name: "Main Triage Desk"
          description: "Primary service desk"
          manager_id: "manager-1"
          manager_name: "Alex Johnson"
        - id: "window-2"
          name: "Secondary Triage Desk"
          description: "Overflow service desk"
          manager_id: "manager-2"
          manager_name: "Jamie Smith"

logging:
  level: "info"   # Less verbose logging for production
  format: "json"  # JSON format for log aggregation

external_api:
  user_services_url: "https://private-4a985-invoice19.apiary-mock.com/waiting-room/medical/services"  # Production external API
  timeout_seconds: 15
  retry_attempts: 3
