# Development configuration for Waiting Room System

server:
  port: 8080
  host: "localhost"
  
database:
  mongodb:
    uri: "mongodb://admin:admin@localhost:27017/waiting_room_dev?authSource=admin"
    database: "waiting_room_dev"
    
cors:
  allowed_origins:
    - "http://localhost:4200"
    - "http://localhost:4201"
    - "http://localhost:4203"
    - "http://localhost:4204"
    - "http://localhost:3000"  # Additional dev server
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
    - "PATCH"
  allowed_headers:
    - "*"

websocket:
  enabled: true
  path: "/ws/queue"

rooms:
  default_room: "triage-1"  # Default room for development
  allow_wildcard: true      # Allow any room ID for development

logging:
  level: "debug"  # More verbose logging for development
  format: "text"
