# Development configuration for Waiting Room System

server:
  port: 8080
  host: "localhost"
  
database:
  mongodb:
    uri: "mongodb://admin:admin@localhost:27017/waiting_room_dev?authSource=admin"
    database: "waiting_room_dev"
    
deepl:
  api_key: "1937e097-93e4-46ba-ba89-4c9697b85fd7:fx"
  
cors:
  allowed_origins:
    - "http://localhost:4200"
    - "http://localhost:4201"
    - "http://localhost:4203"
    - "http://localhost:4204"
    - "http://localhost:3000"  # Additional dev server
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
    - "PATCH"
  allowed_headers:
    - "*"

websocket:
  enabled: true
  path: "/ws/queue"

rooms:
  default_room: "triage-1"
  allow_wildcard: false
  rooms:
    - id: "triage-1"
      name: "Triage Room"
      service_points:
        - id: "window-1"
          name: "Main Triage Desk"
          description: "Primary service desk"
          manager_id: "manager-1"
          manager_name: "Alex Johnson"
        - id: "window-2"
          name: "Secondary Triage Desk"
          description: "Overflow service desk"
          manager_id: "manager-2"
          manager_name: "Jamie Smith"

logging:
  level: "debug"  # More verbose logging for development
  format: "text"

external_api:
  user_services_url: "https://private-4a985-invoice19.apiary-mock.com/waiting-room/medical/services"  # Mock external API for development
  timeout_seconds: 5
  retry_attempts: 2
